on:
  push:
    branches: [main, master]

name: publish-proposal

jobs:
  render-proposal:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write 
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Instalar Node.js (Requerido por las nuevas versiones)
        uses: actions/setup-node@v2
        with:
          node-version: '24'
        
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true
          
      - name: Render and publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: "isc-proposal.qmd"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
